### ISSUE TITLE
Purge by bucket id support

### ISSUE THREAD

**Issue by damianh** [NEventStore/NEventStore.Persistence.RavenDB#1]
(Issue imported from https://github.com/NEventStore/NEventStore/issues/231 )

**Comment by kblooie** [comment]
@Iridio It looks like you added support for this, but there's a todo in the method. I'm assuming because the shared acceptance tests don't explicitly test for purging by bucketId? 

Should we close this?

`//TODO: To test -> Edited index by adding bucketId and streamId`

**Comment by Iridio** [comment]
You are correct. It was a reminder.
